name: sdk_a3f011_cpu1
version: v0.0.0
description: ""
tag: ""
keywords: ~
author:
  name: ""
license: ""
homepage: ~
type: sdk
depends:
  - a3f011_cpu1_chip: v0.0.0
  - a3f011_cpu1_evb: v0.0.0
  - console: v0.0.0
  - csi: v0.0.0
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
build_config:
  include: ~
  internal_include: ~
  cflag: ""
  cxxflag: ""
  asmflag: ""
  define: ~
  libs: ~
  libpath: ~
source_file: ~
def_config: ~
install: ~
depends_forward:
  - a3f011_cpu1_chip: v0.0.0
  - a3f011_cpu1_evb: v0.0.0
  - console: v0.0.0
  - csi: v0.0.0